package com.myspace.tests;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Client implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	private java.lang.Integer id;
	@org.kie.api.definition.type.Label(value = "Address")
	private java.lang.String address;

	public Client() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public Client(java.lang.String name, java.lang.Integer id,
			java.lang.String address) {
		this.name = name;
		this.id = id;
		this.address = address;
	}

}