package com.myspace.tests;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Invoice implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Client")
	private com.myspace.tests.Client client;
	private java.util.Date date;
	private java.util.List<com.myspace.tests.Line> lines;
	private java.lang.Integer total;

	public Invoice() {
	}

	public com.myspace.tests.Client getClient() {
		return this.client;
	}

	public void setClient(com.myspace.tests.Client client) {
		this.client = client;
	}

	public java.util.Date getDate() {
		return this.date;
	}

	public void setDate(java.util.Date date) {
		this.date = date;
	}

	public java.util.List<com.myspace.tests.Line> getLines() {
		return this.lines;
	}

	public void setLines(java.util.List<com.myspace.tests.Line> lines) {
		this.lines = lines;
	}

	public java.lang.Integer getTotal() {
		return this.total;
	}

	public void setTotal(java.lang.Integer total) {
		this.total = total;
	}

	public Invoice(com.myspace.tests.Client client, java.util.Date date,
			java.util.List<com.myspace.tests.Line> lines,
			java.lang.Integer total) {
		this.client = client;
		this.date = date;
		this.lines = lines;
		this.total = total;
	}

}